In [1]:
[[11,12,13,14,15],[11,12,13,14,15],[11,12,13,14,15]]

[[11, 12, 13, 14, 15], [11, 12, 13, 14, 15], [11, 12, 13, 14, 15]]

In [19]:
import numpy
n=numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [13]:
type(n)

numpy.ndarray

In [20]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [23]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [25]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [27]:
m=numpy.asarray([[11,12,13,14,15],[11,12,13,14,15],[11,12,13,14,15]])

In [29]:
m

array([[11, 12, 13, 14, 15],
       [11, 12, 13, 14, 15],
       [11, 12, 13, 14, 15]])

In [30]:
type(m)

numpy.ndarray

In [32]:
print(m)

[[11 12 13 14 15]
 [11 12 13 14 15]
 [11 12 13 14 15]]


In [34]:
m[0][3]

14

In [39]:
import os
os.listdir()

['.ipynb_checkpoints', 'smallgray.png', 'Untitled.ipynb']

In [43]:
import cv2

In [48]:
im_g=cv2.imread("smallgray.png",0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [51]:
cv2.imwrite("newgray.png",im_g)

True

In [71]:
im_g[0:3,1:3]

array([[158, 104],
       [125, 255],
       [134, 255]], dtype=uint8)

In [73]:
im_g[2,4]

182

In [80]:
print("Print by row:")
for i in im_g:
    print(i)

Print by row:
[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [84]:
print("Print by column using transpose:")
for i in im_g.T:
    print(i)

Print by column using transpose:
[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [87]:
print("Print value for each pixel:")
for i in im_g.flat:
    print(i)

Print value for each pixel:
187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [89]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [90]:
print("Stack the array horizontally:")
imh=numpy.hstack((im_g,im_g))
print(imh)

Stack the array horizontally:
[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [91]:
print("Stack the array vertically:")
imv=numpy.vstack((im_g,im_g))
print(imv)

Stack the array vertically:
[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [93]:
print("Split the array horizontally:")
ish=numpy.hsplit(imh,5)
print(ish)

Split the array horizontally:
[array([[187, 158],
       [198, 125],
       [209, 134]], dtype=uint8), array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8), array([[143, 187],
       [147, 198],
       [182, 209]], dtype=uint8), array([[158, 104],
       [125, 255],
       [134, 255]], dtype=uint8), array([[121, 143],
       [255, 147],
       [ 97, 182]], dtype=uint8)]


In [95]:
print("Split the array vertically:")
isv=numpy.hsplit(imv,5)
print(isv)

Split the array vertically:
[array([[187],
       [198],
       [209],
       [187],
       [198],
       [209]], dtype=uint8), array([[158],
       [125],
       [134],
       [158],
       [125],
       [134]], dtype=uint8), array([[104],
       [255],
       [255],
       [104],
       [255],
       [255]], dtype=uint8), array([[121],
       [255],
       [ 97],
       [121],
       [255],
       [ 97]], dtype=uint8), array([[143],
       [147],
       [182],
       [143],
       [147],
       [182]], dtype=uint8)]


In [97]:
ish[0]

array([[187, 158],
       [198, 125],
       [209, 134]], dtype=uint8)